[workspace]
members = [
    "crates/sentinel_core",
    "crates/sentinel_store",
    "crates/sentinel_identity",
    "crates/sentinel_api",
    "crates/sentinel_cli",
    "crates/sentinel_bench",
    "crates/sentinel_policy"
    ,"crates/sentinel_artifacts"
]

[profile.dev]
debug = true

[profile.release]
debug = false
